sensor:
  - name: wlanthermo_channel_1_change
    platform: statistics
    entity_id: sensor.wlanthermo_channel_1_all
    state_characteristic: change_second
    max_age:
      minutes: 30
    precision: 10
    sampling_size: 300

  - name: wlanthermo_channel_2_change
    platform: statistics
    entity_id: sensor.wlanthermo_channel_2_all
    state_characteristic: change_second
    max_age:
      minutes: 30
    precision: 10
    sampling_size: 300

  - name: wlanthermo_channel_3_change
    platform: statistics
    entity_id: sensor.wlanthermo_channel_3_all
    state_characteristic: change_second
    max_age:
      minutes: 30
    precision: 10
    sampling_size: 300

  - name: wlanthermo_channel_4_change
    platform: statistics
    entity_id: sensor.wlanthermo_channel_4_all
    state_characteristic: change_second
    max_age:
      minutes: 30
    precision: 10
    sampling_size: 300

  - name: wlanthermo_channel_5_change
    platform: statistics
    entity_id: sensor.wlanthermo_channel_5_all
    state_characteristic: change_second
    max_age:
      minutes: 30
    precision: 10
    sampling_size: 300

  - name: wlanthermo_channel_6_change
    platform: statistics
    entity_id: sensor.wlanthermo_channel_6_all
    state_characteristic: change_second
    max_age:
      minutes: 30
    precision: 10
    sampling_size: 300

  - name: wlanthermo_channel_7_change
    platform: statistics
    entity_id: sensor.wlanthermo_channel_7_all
    state_characteristic: change_second
    max_age:
      minutes: 30
    precision: 10
    sampling_size: 300

  - name: wlanthermo_channel_8_change
    platform: statistics
    entity_id: sensor.wlanthermo_channel_8_all
    state_characteristic: change_second
    max_age:
      minutes: 30
    precision: 10
    sampling_size: 300

  - name: wlanthermo_channel_9_change
    platform: statistics
    entity_id: sensor.wlanthermo_channel_9_all
    state_characteristic: change_second
    max_age:
      minutes: 30
    precision: 10
    sampling_size: 300

  - name: wlanthermo_pitmaster_value_avg
    platform: statistics
    entity_id: sensor.wlanthermo_pitmaster_value
    state_characteristic: average_linear
    max_age:
      minutes: 30
    sampling_size: 20
    precision: 2
